### ISSUE TITLE
Connections for dependencies are not loaded

### ISSUE THREAD

**Issue by digikar99** [gwkkwg/asdf-system-connections#3]
Suppose I have systems defined as follows:

test-system-a.asd:

```lisp
(defsystem "test-system-a"
  :components ((:file "test-system-a"))
  :defsystem-depends-on ("asdf-system-connections"))

(defsystem-connection "test-system-a/b"
  :requires ("test-system-a" "test-system-b")
  :components ((:file "test-system-ab")))
```

test-system-b.asd:

```lisp
(defsystem "test-system-b"
  :components ((:file "test-system-b")))
```

test-system-c.asd:

```lisp
(defsystem "test-system-c"
  :depends-on ("test-system-a"
               "test-system-b")
  :components ((:file "test-system-c")))
```

Then, loading system `test-system-c` loads `test-system-a` and `test-system-b` but not their connection `test-system-a/b`. It would be great if the connections for dependencies (and their dependencies in turn) are loaded too.

The files are attached with this issue: [test-systems.tar.gz](https://github.com/gwkkwg/asdf-system-connections/files/14274814/test-systems.tar.gz)

**Comment by digikar99** [comment]
The issue does not occur if `asdf-system-connections` is loaded prior to loading system `test-system-c` above, or equivalently, modifying the test-system-c.asd to:

```lisp
(defsystem "test-system-c"
  :depends-on ("test-system-a"
               "test-system-b")
  :defsystem-depends-on ("asdf-system-connections")
  :components ((:file "test-system-c")))
```

This atleast works as a temporary fix, but this means that every user of a system using asdf-system-connections must be aware of asdf-system-connections. In a way, I find it a good practice to notice the dependencies of your dependencies. That way. one can see if they want to cut something down to make dependencies more minimal, and thus, make the project more maintainable in the long run.

**Comment by gwkkwg** [comment]
I agree with you but no longer maintain this code. Feel free to take it over if you’d like.

**Comment by digikar99** [comment]
Thanks for getting back! In that case, you can transfer the repository ownership to [lisp-maintainers](https://github.com/lisp-maintainers/) - me and a few other lispers maintain over there. That way, even if I become passive in lisp some day, someone else can maintain it.

**Comment by gwkkwg** [comment]
GitHub says that I “don’t have permission to create public repositories on lisp-maintainers.”Please advise,Carefully crafted using only the finest bytes and freshest electrons.On Feb 15, 2024, at 11:48 PM, Shubhamkar Ayare ***@***.***> wrote:﻿
Thanks for getting back! In that case, you can transfer the repository ownership to lisp-maintainers - me and a few other lispers maintain over there. That way, even if I become passive in lisp some day, someone else can maintain it.

**Comment by digikar99** [comment]
I have sent you an invitation - accepting it should let you create new repositories at lisp-maintainers.

**Comment by gwkkwg** [comment]
Great. Thank you and … done.

**Comment by digikar99** [comment]
Thanks a lot to you for this project :)!

**Comment by digikar99** [comment]
I have been trying things in the [load-systems-driven](https://github.com/lisp-maintainers/asdf-system-connections/tree/load-system-driven) branch and the linked PR. Unfortunately, this way of fixing this issue (and perhaps any other way too!) can break other systems.

The current design lets users implicitly assume a certain load order. Fixing this issue requires changing the load order. However, if this load order changes, there's no telling if the 332 quicklisp systems that directly or indirectly depend on asdf-system-connections continue to load. And perhaps, there will be other systems not in quicklisp too. Some of these systems might as well be unmaintained.

I'll instead fix this issue in a fork of this repository and only issue non-breaking fixes to this repository.
